// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // DIRECT_URL = non-pooled Supabase connection (port 5432).
    // Required for `prisma migrate deploy` which needs session-level advisory
    // locks that PgBouncer transaction mode (port 6543) does not support.
    // Runtime queries use DATABASE_URL (port 6543) via src/utils/prisma.ts pool.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
