// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Using DATABASE_URL (pooler, port 6543) so migrations work without IP allowlisting.
    // Switch back to DIRECT_URL if session-level locks are needed.
    url: process.env["DATABASE_URL"],
  },
});
