// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations require session-level advisory locks, which the transaction-mode
    // pooler (port 6543) does NOT support. Use DIRECT_URL (port 5432 session
    // pooler or the direct host). Falls back to DATABASE_URL if not set.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
